### ISSUE TITLE
2.8.1 - Error during PDF generation / Info desk

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1578]
Got a few errors like these when generation PDF files. Seems to be because he can't find info desk ? 

en api/en/treks/921158/tour-of-vieux-chaillol-stage-1-out-of-5.pdf ...ERROR 2016-02-04 23:16:41,450 mapentity.helpers Request on http://127.0.0.1:8001/?url=http%3A//XX.XX.XXX.XXX//trek/921158/%3Flang%3Den%26context%3D%257B%2522print%2522%253A%2520true%252C%2520%2522mapsize%2522%253A%2520%257B%2522width%2522%253A%2520800%252C%2520%2522height%2522%253A%2520624.113475177305%257D%257D&selector=.map-panel&waitfor=.poi_enum_loaded.services_loaded.info_desks_loaded.ref_points_loaded returned empty content
Traceback (most recent call last):
  File "/home/sentiers/Geotrek/lib/eggs/mapentity-2.7.1-py2.7.egg/mapentity/helpers.py", line 154, in download_to_stream
    assert len(source.content) > 0, content_error
AssertionError: Request on http://127.0.0.1:8001/?url=http%3A//XX.XX.XXX.XXX/trek/921158/%3Flang%3Den%26context%3D%257B%2522print%2522%253A%2520true%252C%2520%2522mapsize%2522%253A%2520%257B%2522width%2522%253A%2520800%252C%2520%2522height%2522%253A%2520624.113475177305%257D%257D&selector=.map-panel&waitfor=.poi_enum_loaded.services_loaded.info_desks_loaded.ref_points_loaded returned empty content
failed (Request on http://127.0.0.1:8001/?url=http%3A//XX.XX.XXX.XXX//trek/921158/%3Flang%3Den%26context%3D%257B%2522print%2522%253A%2520true%252C%2520%2522mapsize%2522%253A%2520%257B%2522width%2522%253A%2520800%252C%2520%2522height%2522%253A%2520624.113475177305%257D%257D&selector=.map-panel&waitfor=.poi_enum_loaded.services_loaded.info_desks_loaded.ref_points_loaded returned empty content)

**Comment by camillemonchicourt** [comment]
Oh no, rather look like it is when trying to load ref points.
Indeed we dont have any ref points on trek maps.

**Comment by gutard** [comment]
The debugging  of PDF generation is very tricky. This error has a lot of possible causes. For example missing or wrong --url argument, wrong IGN key, wrong tiles configuration, too many requests in parallel, low network throughput, etc.

Before opening the issue, did you check your hypothesis by adding an info desk and a reference point ? Does it work or not ?

If it fails on command line, does it work in UI ?

**Comment by camillemonchicourt** [comment]
OK I opened it as I didnt got this error in previous versions and launched the same synchro command as previously. And it happened for ALL treks PDF generation while I had no problem previously.

I misinterpreteded the error message certainly. 

But yes, I will investigate deeper later to see if this is not by my side.

**Comment by gutard** [comment]
The only bug I know related to this is #1579 but it does not arise during a synchronization because the only published content is synchronized.

**Comment by camillemonchicourt** [comment]
With 2.10.1 I get a lot less error messages like this one during Grand Tour des Ecrins synchronization. I had more than 100 errors when synchronizing with 2.10.0. I guess it is becasue most of our treks on this portal were children (unpublished then). 

With 2.10.1, I get just 2 or 3 errors at each synchronization like this :

**SUBJECT :**
```
[Geotrek] ERROR: HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /?url=http%3A//87.98.145.147/trek/939587/%3Flang%3Dfr%26context%3D%257B%2522print%2522%253A%2520true%252C%2520%2522mapsize%2522%253A%2520%257B%2522width%2522%253A%2520800%252C%2520%2522height%2522%253A%2520624.113475177305%257D%257D&selector=.map-panel&waitfor=.poi_enum_loaded.services_loaded.info_desks_loaded.ref_points_loaded (Caused by <class 'httplib.BadStatusLine'>: '')
```

**MESSAGE :**
```
Traceback (most recent call last):

  File "/home/sentiers/Geotrek/lib/eggs/mapentity-2.7.1-py2.7.egg/mapentity/helpers.py", line 148, in download_to_stream
    source = requests.get(url, headers=headers)

  File "/home/sentiers/Geotrek/lib/eggs/requests-1.2.3-py2.7.egg/requests/api.py", line 55, in get
    return request('get', url, **kwargs)

  File "/home/sentiers/Geotrek/lib/eggs/requests-1.2.3-py2.7.egg/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)

  File "/home/sentiers/Geotrek/lib/eggs/requests-1.2.3-py2.7.egg/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)

  File "/home/sentiers/Geotrek/lib/eggs/requests-1.2.3-py2.7.egg/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)

  File "/home/sentiers/Geotrek/lib/eggs/requests-1.2.3-py2.7.egg/requests/adapters.py", line 327, in send
    raise ConnectionError(e)

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /?url=http%3A//87.98.145.147/trek/939587/%3Flang%3Dfr%26context%3D%257B%2522print%2522%253A%2520true%252C%2520%2522mapsize%2522%253A%2520%257B%2522width%2522%253A%2520800%252C%2520%2522height%2522%253A%2520624.113475177305%257D%257D&selector=.map-panel&waitfor=.poi_enum_loaded.services_loaded.info_desks_loaded.ref_points_loaded (Caused by <class 'httplib.BadStatusLine'>: '')


Request repr() unavailable.
```

**Comment by pierreloicq** [comment]
Hi Camille,
Did you end up by resolving this problem ?
Thank you

**Comment by pierreloicq** [comment]
Thank you. On which version of GTA are you ?

**Comment by camillemonchicourt** [comment]
2.34.0. 
I checked in my synchronization logs and I confirm that I dont have these kind of error messages anymore.
Which messages or errors do you have and in which case ?

**Comment by pierreloicq** [comment]
Thank you.
I have the first log mentioned above on my production server and the second one on my test server. 
The details are here : https://github.com/GeotrekCE/Geotrek-admin/issues/2358
I will try 2.34.0 to see if it's not a bug of my version (2.38.1)

**Comment by camillemonchicourt** [comment]
If you have the problem in 2.38, I dont see any reason that it is not in 2.34

**Comment by pierreloicq** [comment]
Could you tell me what parameters you have in the file /opt/geotrek-admin/var/conf/env ?
POSTGRES_HOST
SERVER_NAME
RANDO_SERVER_NAME
CONVERSION_HOST
CAPTURE_HOST

and the content of your files
/etc/hosts
/etc/hostname
/etc/hosts.allow

Thank you

**Comment by camillemonchicourt** [comment]
J'ai jamais touché à ces paramètres et éléments, tout est par défaut.

Dans ``/opt/geotrek-admin/var/conf/env`` : 

```
POSTGRES_HOST="localhost"
SERVER_NAME="_"
RANDO_SERVER_NAME="*"
CONVERSION_HOST="localhost"
CAPTURE_HOST="localhost"
```

Dans ``etc/hosts`` :

```
127.0.0.1	localhost
127.0.1.1	geotrek-admin

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

Dans ``etc/hostname``

```
geotrek-admin
```

Dans ``etc/hosts.allow``

```
# /etc/hosts.allow: list of hosts that are allowed to access the system.
#                   See the manual pages hosts_access(5) and hosts_options(5).
#
# Example:    ALL: LOCAL @some_netgroup
#             ALL: .foobar.edu EXCEPT terminalserver.foobar.edu
#
# If you're going to protect the portmapper use the name "rpcbind" for the
# daemon name. See rpcbind(8) and rpc.mountd(8) for further information.
```

**Comment by pierreloicq** [comment]
Dacc, merci beaucoup
