### ISSUE TITLE
WEASYPRINT - Pdf Export character error - All strings must be XML compatible

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek#1591]
My synchronization gets an error when generating one of the trek public PDF. 

Looks like somethng like https://github.com/html5lib/html5lib-python/issues/96

But I cant' find which character makes the problem. 

The trek is http://www.grand-tour-ecrins.fr/a-pied/du-lac-de-la-muzelle-au-bourg-doisans-par-le-col-du-vallon-etape-du-gr-54/

ERROR : 
```
fr api/fr/treks/939601/du-lac-de-la-muzelle-au-bourg-doisans-par-le-col-du-vallon-etape-du-gr-54.pdf ...Traceback (most recent call last):
  File "./bin/django", line 101, in <module>
    sys.exit(django.core.management.execute_from_command_line(sys.argv))
  File "/home/sentiers/Geotrek/lib/eggs/Django-1.6.5-py2.7.egg/django/core/management/__init__.py", line                                       399, in execute_from_command_line
    utility.execute()
  File "/home/sentiers/Geotrek/lib/eggs/Django-1.6.5-py2.7.egg/django/core/management/__init__.py", line                                       392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sentiers/Geotrek/lib/eggs/Django-1.6.5-py2.7.egg/django/core/management/base.py", line 242,                                       in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/sentiers/Geotrek/lib/eggs/Django-1.6.5-py2.7.egg/django/core/management/base.py", line 285,                                       in execute
    output = self.handle(*args, **options)
  File "/home/sentiers/Geotrek/geotrek/tourism/management/commands/sync_rando.py", line 39, in handle
    super(Command, self).handle(*args, **options)
  File "/home/sentiers/Geotrek/geotrek/trekking/management/commands/sync_rando.py", line 502, in handle
    self.sync()
  File "/home/sentiers/Geotrek/geotrek/tourism/management/commands/sync_rando.py", line 149, in sync
    super(Command, self).sync()
  File "/home/sentiers/Geotrek/geotrek/trekking/management/commands/sync_rando.py", line 447, in sync
    self.sync_trekking(lang)
  File "/home/sentiers/Geotrek/geotrek/trekking/management/commands/sync_rando.py", line 374, in sync_tre                                      kking
    self.sync_trek(lang, trek)
  File "/home/sentiers/Geotrek/geotrek/tourism/management/commands/sync_rando.py", line 162, in sync_trek
    super(Command, self).sync_trek(lang, trek)
  File "/home/sentiers/Geotrek/geotrek/trekking/management/commands/sync_rando.py", line 294, in sync_tre                                      k
    self.sync_trek_pdf(lang, trek)
  File "/home/sentiers/Geotrek/geotrek/trekking/management/commands/sync_rando.py", line 231, in sync_tre                                      k_pdf
    self.sync_object_view(lang, obj, view, '{obj.slug}.pdf')
  File "/home/sentiers/Geotrek/geotrek/trekking/management/commands/sync_rando.py", line 225, in sync_obj                                      ect_view
    self.sync_view(lang, view, name, zipfile=zipfile, pk=obj.pk, **kwargs)
  File "/home/sentiers/Geotrek/geotrek/trekking/management/commands/sync_rando.py", line 175, in sync_vie                                      w
    response.render()
  File "/home/sentiers/Geotrek/lib/eggs/Django-1.6.5-py2.7.egg/django/template/response.py", line 105, in                                       render
    self.content = self.rendered_content
  File "/home/sentiers/Geotrek/lib/eggs/django_weasyprint-0.1-py2.7.egg/django_weasyprint/views.py", line                                       21, in rendered_content
    pdf = weasyprint.HTML(string=html, base_url=base_url).write_pdf()
  File "/home/sentiers/Geotrek/lib/eggs/WeasyPrint-0.23-py2.7.egg/weasyprint/__init__.py", line 91, in __                                      init__
    namespaceHTMLElements=False)
  File "/home/sentiers/Geotrek/lib/eggs/html5lib-1.0b8-py2.7.egg/html5lib/html5parser.py", line 29, in pa                                      rse
    return p.parse(doc, encoding=encoding)
  File "/home/sentiers/Geotrek/lib/eggs/html5lib-1.0b8-py2.7.egg/html5lib/html5parser.py", line 236, in p                                      arse
    parseMeta=parseMeta, useChardet=useChardet)
  File "/home/sentiers/Geotrek/lib/eggs/html5lib-1.0b8-py2.7.egg/html5lib/html5parser.py", line 94, in _p                                      arse
    self.mainLoop()
  File "/home/sentiers/Geotrek/lib/eggs/html5lib-1.0b8-py2.7.egg/html5lib/html5parser.py", line 195, in m                                      ainLoop
    new_token = phase.processCharacters(new_token)
  File "/home/sentiers/Geotrek/lib/eggs/html5lib-1.0b8-py2.7.egg/html5lib/html5parser.py", line 1003, in                                       processCharacters
    self.tree.insertText(token["data"])
  File "/home/sentiers/Geotrek/lib/eggs/html5lib-1.0b8-py2.7.egg/html5lib/treebuilders/_base.py", line 32                                      0, in insertText
    parent.insertText(data)
  File "/home/sentiers/Geotrek/lib/eggs/html5lib-1.0b8-py2.7.egg/html5lib/treebuilders/etree_lxml.py", li                                      ne 240, in insertText
    builder.Element.insertText(self, data, insertBefore)
  File "/home/sentiers/Geotrek/lib/eggs/html5lib-1.0b8-py2.7.egg/html5lib/treebuilders/etree.py", line 10                                      8, in insertText
    self._element.text += data
  File "lxml.etree.pyx", line 951, in lxml.etree._Element.text.__set__ (src/lxml/lxml.etree.c:46353)
  File "apihelpers.pxi", line 695, in lxml.etree._setNodeText (src/lxml/lxml.etree.c:20953)
  File "apihelpers.pxi", line 683, in lxml.etree._createTextNode (src/lxml/lxml.etree.c:20829)
  File "apihelpers.pxi", line 1393, in lxml.etree._utf8 (src/lxml/lxml.etree.c:27125)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

**Comment by gutard** [comment]
How to fix : 

1. get lang and id of trek from sync command output. In this example fr and 939601,
2. get json for this trek by replacing domain, lang and id in `http://<my.domain>/api/<lang>/treks/<id>.json`. In this example `http://87.98.145.147/api/fr/treks/939601.json`
3. search for non-printable chars : \u000x (x = 0 or 1, 2, 3, 4, 5, 6, 7, 8, 9, a, b, c, d, e, f), or \u007f, or \b. In this example: "...canal du \u0007Fournol\b et,..."
4. got to Geotrek-Admin and edit trek to erase and rewrite manually parts around these non-printable chars

**Comment by camillemonchicourt** [comment]
OK thanks. So it is due to content and not Geotrek.
